[package]
name = "Detection_System"
version = "1.4.0"
edition = "2021"


[dependencies]
aes = "0.8"
cbc = "0.1"
hex = "0.4"
rand = "0.9.2" 
base64 = "0.22.1"
chrono = "0.4.42"

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1
panic = 'abort'
strip = true
